project:
  type: website

website:
  title: "PORTFOLIO"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - page.qmd
      - Code.qmd
      - youtube.qmd
      
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

